register_module "core"
register_module "helpers"
register_module "git"
register_module "docker"
register_module "brew"
register_module "colima"
register_module "nvim"
register_module "prompt-starship"
