#!/bin/bash

CONTAINER_SERVICES_NETWORK="10.0.0.0/24"
CONTAINER_DEV_NETWORK="10.0.1.0/24"
CONTAINER_QUIET_DEV_NETWORK="10.0.2.0/24"
DNS_SERVER_IP=10.0.0.3
DHCP_SERVER_IP=10.0.0.4
WIRELESS_NETWORK_INTERFACE_NAME=wlan0
WIRED_NETWORK_INTERFACE_NAME=eno0

# Drop all forward requests by default
iptables -P FORWARD DROP

# Allow existing or related connections, this will ensure things like icmp can respond to request
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

iptables -A FORWARD -s $CONTAINER_SERVICES_NETWORK -d $CONTAINER_DEV_NETWORK -j ACCEPT
iptables -A FORWARD -s $CONTAINER_SERVICES_NETWORK -d $CONTAINER_QUIET_DEV_NETWORK -j ACCEPT

# Allow DNS (10.0.0.3) - UDP/TCP port 53
iptables -A FORWARD -s $CONTAINER_DEV_NETWORK -d $DNS_SERVER_IP -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -s $CONTAINER_DEV_NETWORK -d $DNS_SERVER_IP -p tcp --dport 53 -j ACCEPT

iptables -A FORWARD -s $CONTAINER_QUIET_DEV_NETWORK -d $DNS_SERVER_IP -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -s $CONTAINER_QUIET_DEV_NETWORK -d $DNS_SERVER_IP -p tcp --dport 53 -j ACCEPT


iptables -A FORWARD -s $CONTAINER_DEV_NETWORK -d $DHCP_SERVER_IP -p udp --dport 67:68 -j ACCEPT
iptables -A FORWARD -s $CONTAINER_DEV_NETWORK -d $DHCP_SERVER_IP -p udp --sport 67:68 -j ACCEPT

iptables -A FORWARD -s $CONTAINER_QUIET_DEV_NETWORK -d $DHCP_SERVER_IP -p udp --dport 67:68 -j ACCEPT
iptables -A FORWARD -s $CONTAINER_QUIET_DEV_NETWORK -d $DHCP_SERVER_IP -p udp --sport 67:68 -j ACCEPT



iptables -A FORWARD  -s $CONTAINER_SERVICES_NETWORK -o $WIRELESS_NETWORK_INTERFACE_NAME  -j ACCEPT

iptables -A FORWARD  -s $CONTAINER_SERVICES_NETWORK -o $WIRED_NETWORK_INTERFACE_NAME  -j ACCEPT

iptables -A FORWARD  -s $CONTAINER_DEV_NETWORK -o $WIRELESS_NETWORK_INTERFACE_NAME  -j ACCEPT

iptables -A FORWARD  -s $CONTAINER_DEV_NETWORK -o $WIRED_NETWORK_INTERFACE_NAME  -j ACCEPT




