$workspaceMod = CTRL_SHIFT

$mainWorkspace=1
$browserWorkSpace=2
$sysMonitorWorkspace=3
$musicWorkspace=4
$notesWorkspace=5
$socialWorkspace=6
$broadcastingWorkspace=7
$videoEditorWorkspace=8
$streamBrowserWorkspace=9
$commsWorkspace=10

workspace=$mainWorkspace,defaultName:Main(1), default:true, monitor:HDMI-A-3
workspace=$browserWorkSpace,defaultName:Browser(2), monitor:HDMI-A-3
workspace=$sysMonitorWorkspace,defaultName:SysMonitor(3), monitor:eDP-1
workspace=$musicWorkspace,defaultName:Music(4), monitor:eDP-1
workspace=$notesWorkspace,defaultName:Notes(5), monitor:HDMI-A-3
workspace=$socialWorkspace,defaultName:Social(6), monitor:HDMI-A-3
workspace=$broadcastingWorkspace,defaultName:Broadcast(7),monitor:HDMI-A-3
workspace=$videoEditorWorkspace,defaultName:VEditor(8),monitor:HDMI-A-3
workspace=$streamBrowserWorkspace,defaultName:StrBrowser(9), monitor:eDP-1
workspace=$commsWorkspace,defaultName:Comms($commsWorkspace), monitor:eDP-1

