# ALIASES
alias gs="git status"
alias gpr="git pull --rebase"
alias zource="source ~/.zshrc"
alias zv="nvim ~/.zshrc"
alias ls="ls -alhG --color=auto"
alias v="nvim"
alias push="git push"
alias kn="kubectl neat"
alias k="kubectl"
alias kgp="kubectl get pods" 
alias kgd="kubectl get deployments"
